#!/bin/bash 
#
# working with arrays
# Vandita Sharma
#

array1[0]=one 
array1[1]=1 
echo ${array1[0]} 
echo ${array1[1]} 

UUID[0]=1
echo ${UUID[0]}

for i in {1..3}
do
	UUID1[$i]=$(uuidgen)
	echo ${UUID1[$i]}
done